### ISSUE TITLE
add serum idl (back?)

### ISSUE THREAD

**Issue by snoworly** [gagliardetto/anchor-go#11]
Huge fan of your Solana toolchains @gagliardetto! Could we add a serum IDL again? I found it in the history but I'm not sure why it was removed. Was it manually constructed?

https://github.com/gagliardetto/anchor-go/commit/3f23d3a7b89f83ad1e71ea470a21a9e1a58eca7a

**Comment by gagliardetto** [comment]
> Huge fan of your Solana toolchains @gagliardetto! 

Thanks!

> Could we add a serum IDL again?

Added back: https://github.com/gagliardetto/anchor-go/blob/main/idl/serum/dex.json

There's also a (very rough) serum client written in Go: https://github.com/gagliardetto/serum-go

**Comment by snoworly** [comment]
thanks for that! We're using your serum client for a while already, works without issues 👍
