### ISSUE TITLE
How to specify remainingAccounts?

### ISSUE THREAD

**Issue by archseer** [gagliardetto/anchor-go#12]
We use an instruction that uses `ctx.remaining_accounts` internally. How do we specify those remaining accounts? They're passed as a separate field in `anchor.js`.

**Comment by gagliardetto** [comment]
Instructions have an `Append` method.

Example: `instr.Append(solana.Meta(pubkey).WRITE().SIGNER())`

**Comment by archseer** [comment]
Thanks! That helped.
