### ISSUE TITLE
Method issue when includes 0-9

### ISSUE THREAD

**Issue by evulse** [gagliardetto/anchor-go#4]
If a method ends in a number "doSomething2" then the AnchorTypeIDEncoding is wrong as it treats it as do_something_2 instead of the required do_something2

I only needed to generate once so I didn't really solve this correctly as it's across multiple repos

https://github.com/gagliardetto/anchor-go/pull/3

**Comment by gagliardetto** [comment]
Fixed in https://github.com/gagliardetto/anchor-go/pull/5/files

**Comment by gagliardetto** [comment]
Fixed by https://github.com/gagliardetto/anchor-go/pull/5
