### ISSUE TITLE
Tuple support

### ISSUE THREAD

**Issue by FlowGoCrazy** [gagliardetto/anchor-go#6]
Any idea when tuple support may be coming? I have some IDLs that I'm unable to convert due to the lack of support. I'd happily offer payment for the addition of this feature and any others that may be required to convert more advanced IDLs.

**Comment by gagliardetto** [comment]
Hey @FlowGoCrazy Please contact me on twitter: https://twitter.com/immaterial_ink

**Comment by godtoy** [comment]
Hey, i have many time to do this if u can give me more detail about tuple.
